sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: 
  - mvn -f ./backend/pom.xml -P frontend clean package

script:
  - docker build -t jianzhichun/danmu-analyzer .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push jianzhichun/danmu-analyzer;
    fi

after_success:
  - mvn -f ./backend/pom.xml clean package jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2
