spring.mvc.async.request-timeout: -1

management.security.enabled: false

server: 
  compression: 
    enabled: true
    mime-types: application/javascript,application/json,text/css,text/html,text/plain